### ISSUE TITLE
Ideas...

### ISSUE THREAD

**Issue by RaveTek** [EaglerDevs/Eaglercraft-1.16.5#2]
got any ideas on how to code the thing?

**Comment by catfoolyou** [comment]
1. stop skidding
2. learn java
3. learn how lax1dude's internals and eaglercraft code works
4. pull MCP for 1.16 out of your ass (MCP only goes up to 1.12)
5. get the sources for all of it's dependencies
6. rewrite everything
7. rewrite it AGAIN to work with teavm's JDK
8. profit

I'm not gonna shit on you because you actually ask about this instead of faking it and being a skid

**Comment by catfoolyou** [comment]
But please take these repos down and stop skidding

**Comment by RaveTek** [comment]
uh, well, FYI: mcp reborn is out, and, FYI: my computer does not support anything like MCP 1.17+. So, BYE! AND WE WILL FIGURE IT OUT ON OUR OWN! WE WILL HUST DELETE SOME OF THE CODE THAT WAS COPIED! BYYYYYYYYYYYYYYYYYYYYYYYYYYYYEEEEEEEEEEEEEEEEEEEEEEEEEEEEE!

**Comment by catfoolyou** [comment]
You still don't know java or teavm's API. No way in hell you can do this from scratch. 

Even I based my 1.12 port off of Lax1dude's internals.
